# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-29 01:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20180929_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='pay_status',
            field=models.CharField(choices=[('TRADE_SUCCESS', '成功'), ('paying', '待支付'), ('TRADE_FINISHED', '交易结束'), ('TRADE_CLOSE', '交易关闭'), ('WAIT_BUYER_PAY', '交易创建')], default='paying', max_length=20, verbose_name='交易状态'),
        ),
    ]
