# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-05 18:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20181006_0210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='pay_status',
            field=models.CharField(choices=[('TRADE_CLOSE', '交易关闭'), ('TRADE_SUCCESS', '成功'), ('TRADE_FINISHED', '交易结束'), ('paying', '待支付'), ('WAIT_BUYER_PAY', '交易创建')], default='paying', max_length=20, verbose_name='交易状态'),
        ),
    ]
